#!/bin/sh

# Configuration
BTCXE_HOME=/var/www
BITCOIND=/usr/bin/bitcoind

# Start Bitcoind
$BITCOIND -daemon

# Purge Lockfiles
rm -f $BTCXE_HOME/lock/lock

# Start NodeJS
$BTCXE_HOME/node_start.sh >> $BTCXE_HOME/log/cryptocap.log 2>&1 &
